<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1549392811477' stop='1549392819141'>
    <name>RegForm</name>
    <title>RegForm</title>
    <test-cases>
        <test-case start='1549392811478' status='failed' stop='1549392819140'>
            <name>6/remove user</name>
            <title>6/remove user</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Expected 'user' to be 'User3'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\specs\spec.js:127:46)
                    at C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\selenium-webdriver\lib\promise.js:2974:25)
                    at C:\Users\Дмитрий\Desktop\testapp\testAppExample2\node_modules\selenium-webdriver\lib\promise.js:668:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>